// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkpBIUSHqd6sDvocTuz2w_Ig8Pf3cwAyQ',
    appId: '1:867991877311:web:d0fea7cca9ed66ad9ff80a',
    messagingSenderId: '867991877311',
    projectId: 'app-help-student',
    authDomain: 'app-help-student.firebaseapp.com',
    storageBucket: 'app-help-student.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy2nz_9UeHY7WZG2vfer27vfVkcj3qjAI',
    appId: '1:867991877311:android:ca1e67a5e27cc5c79ff80a',
    messagingSenderId: '867991877311',
    projectId: 'app-help-student',
    storageBucket: 'app-help-student.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBceVfCtWGgELPCK5mBDOBERALbf8ZPsbE',
    appId: '1:867991877311:ios:8bf74845332d0f4e9ff80a',
    messagingSenderId: '867991877311',
    projectId: 'app-help-student',
    storageBucket: 'app-help-student.appspot.com',
    iosClientId: '867991877311-c5dr2111gbp7k0so07gc47hrk3tif01g.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBceVfCtWGgELPCK5mBDOBERALbf8ZPsbE',
    appId: '1:867991877311:ios:8bf74845332d0f4e9ff80a',
    messagingSenderId: '867991877311',
    projectId: 'app-help-student',
    storageBucket: 'app-help-student.appspot.com',
    iosClientId: '867991877311-c5dr2111gbp7k0so07gc47hrk3tif01g.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpStudent',
  );
}
